spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=demodb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin

  mail:
    host: smtp.gmail.com
    port: 587
    username: vothanhphat7480@gmail.com
    password: hoee syxe fenp kjrk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
   jwt:
      secret-key: "357638792F423F4428472B4B6250655368566D597133743677397A2443264629"

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
